name: balade
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2+2

environment:
  sdk: ^3.8.1

dependencies:
  date_field: ^6.0.3+1
  file_picker: ^10.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  google_fonts: ^6.3.0
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  phone_form_field: ^10.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
